name: clean_architecture
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  retrofit: ^4.4.1
  injectable: ^2.5.0
  get_it: ^8.0.2
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  either_dart: ^1.0.0
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.3.0
  copy_with_extension: ^5.0.4
  lottie: ^3.1.2
  gap: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2
  copy_with_extension_gen: ^5.0.4
  injectable_generator: ^2.6.2

flutter:

  uses-material-design: true

  assets:
      - assets/images/

  fonts:
    - family: NotoSansLao
      fonts:
        - asset: assets/fonts/NotoSansLao-Regular.ttf
